name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build client linux
      run: GOOS=linux GOARCH=amd64 go build -v -ldflags "-s -w" -o bin/linux/dtunnel client.go
   
    - name: Build client arm
      run: GOOS=linux GOARCH=arm go build -v -ldflags "-s -w" -o bin/arm/dtunnel client.go

    - name: Build client win
      run: GOOS=windows GOARCH=amd64 go build -v -ldflags "-s -w" -o bin/win/dtunnel client.go
      
    - name: Build server linux
      run: GOOS=linux GOARCH=amd64 go build -v -ldflags "-s -w" -o bin/linux/dtunnel_s server.go
   
    - name: Build server arm
      run: GOOS=linux GOARCH=arm go build -v -ldflags "-s -w" -o bin/arm/dtunnel_s server.go

    - name: Build server win
      run: GOOS=windows GOARCH=amd64 go build -v -ldflags "-s -w" -o bin/win/dtunnel_s server.go
      
    - name: Ls files
      run: ls -lah bin/

